version: '3.9'

services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: lockbox
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: ./backend
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql://postgres:postgres@db:5432/lockbox?schema=public}
      BASE_URL: ${BASE_URL:-http://localhost:8080}
      CORS_ORIGIN: ${CORS_ORIGIN:-http://localhost:8080}
      TELEGRAM_ACCESS_TOKEN: AAFACQAA0um8q4sGWSr9WkT1_kUK-6v5qnCYv5_qG5Ccqg
      TELEGRAM_MOCK_MODE: false
    depends_on:
      db:
        condition: service_healthy
    command: ["sh", "-c", "npx prisma migrate deploy || npx prisma db push; node dist/main.js"]

  nginx:
    build:
      context: ./frontend
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - "8080:80"

volumes:
  db-data:
