name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: SSH Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
     
      
      - name: Prepare SSH key
        run: |
          echo "${{ secrets.DEPLOY_SSH_KEY_B64 }}" | base64 -d > /tmp/github_actions_deploy
          chmod 600 /tmp/github_actions_deploy

      - name: Run remote deploy script
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          port: ${{ secrets.DEPLOY_PORT }}
          key_path: /tmp/github_actions_deploy
          script: |
            export DEPLOY_PATH="${{ secrets.DEPLOY_PATH }}"
            bash "$DEPLOY_PATH/scripts/deploy.sh"
