name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: SSH Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run remote deploy script
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          port: ${{ secrets.DEPLOY_PORT }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            export DEPLOY_PATH="${{ secrets.DEPLOY_PATH }}"
            export DEPLOY_BRANCH="main"
            export DEPLOY_NO_CACHE="${{ secrets.DEPLOY_NO_CACHE }}"
            export DEPLOY_PRUNE="${{ secrets.DEPLOY_PRUNE }}"
            bash "$DEPLOY_PATH/scripts/deploy.sh"
